generate_image:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: yandexgpt_conversation
    prompt:
      required: true
      selector:
        text:
          multiline: true
